products:
    terraform-provider-tenablesc:
        build:
            main-pkg: .
            os-archs:
                - os: darwin
                  arch: amd64
                - os: linux
                  arch: amd64
                - os: windows
                  arch: amd64
        dist:
            disters:
                type: bin
